#!/bin/bash
cd /tmp
cordova create Project
cd Project
cordova platform add ios
cordova platform add android

#cordova plugin add ~/workspace/PhoneGap-Geofencing/
#remove samples from plugin directories
rm -rf `find . -name Sample`
rm -rf `find . -name local.properties`

#remove everything except config.xml from www directory
rm -rf www/css/ www/spec* www/js/ www/index.html www/img/
cp `which ios-sim` .

tar zcvf ../project-template.tar.gz .

cd ..
mvn deploy:deploy-file -Dfile=project-template.tar.gz  -Durl=https://repository.jboss.org/nexus/content/repositories/snapshots/ -DrepositoryId=jboss-snapshots-repository -DgroupId=org.jboss.errai -DartifactId=errai-cordova-template -Dversion=3.0-SNAPSHOT -Dpackaging=tar.gz