#!/bin/bash
if [ -z "$1" ]; then
  echo -e "Version not specified! \nuse: 'cordova-bundle <version number>'";
  exit;
else
  echo "Version to deploy '$1'";
fi

cp pom.xml /tmp
cp AndroidManifest.xml /tmp
PROJECT_DIR=`pwd`
cd /tmp
cordova create Project
cd Project
cordova platform add ios
cordova platform add android
cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.battery-status
cordova plugin add org.apache.cordova.camera
cordova plugin add org.apache.cordova.device-motion
cordova plugin add org.apache.cordova.device-orientation
cordova plugin add org.apache.cordova.console
cordova plugin org.apache.cordova.contacts
cordova plugin org.apache.cordova.dialogs
cordova plugin org.apache.cordova.file
cordova plugin org.apache.cordova.file-transfer

cp ../AndroidManifest.xml platforms/android/CordovaLib/

#cordova plugin add ~/workspace/PhoneGap-Geofencing/
#remove samples from plugin directories
rm -rf `find . -name Sample`
rm -rf `find . -name local.properties`

#remove everything except config.xml from www directory
rm -rf www/css/ www/spec* www/js/ www/index.html www/img/
cp `which ios-sim` .

cp -R $PROJECT_DIR/android-windows/* /tmp/Project/platforms/android/cordova

tar zcvf ../project-template.tar.gz .

cd ..
if [[ "$1" == *SNAPSHOT* ]]
then
  mvn deploy:deploy-file -Dfile=project-template.tar.gz  -Durl=https://repository.jboss.org/nexus/content/repositories/snapshots/ -DrepositoryId=jboss-snapshots-repository -DgroupId=org.jboss.errai -DartifactId=errai-cordova-template -Dversion=$1 -Dpackaging=tar.gz
else
  sed -e "s/\$VERSION/"$1"/g" pom.xml > pomFile.xml
  mvn deploy:deploy-file -Dfile=project-template.tar.gz  -Durl=https://repository.jboss.org/nexus/service/local/staging/deploy/maven2/ -DrepositoryId=jboss-releases-repository -DpomFile=pomFile.xml -Dpackaging=tar.gz
fi
